name: openconnect-client

networks:
  vpn_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.56.11.0/28 # Use /28 for 16 IPs

services:
  vpn:
    container_name: openconnect-client
    build: ubuntu-custom
    image: villcabo/openconnect-client
    restart: unless-stopped
    networks:
      vpn_network:
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      net.ipv4.ip_forward: 1
    volumes:
      - ./start-vpn.sh:/scripts/start-vpn.sh
    environment:
      VPN_HOST: ${VPN_HOST}
      VPN_USER: ${VPN_USER}
      VPN_PASS: ${VPN_PASS}
      VPN_GROUP: ${VPN_GROUP}
      SHARED_IPS: ${SHARED_IPS}
