name: openconnect

networks:
  vpn_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24  # Asegúrate que coincida con tu br-f1d57739c958
          gateway: 172.24.0.1   # Asegúrate que coincida con tu br-f1d57739c958
          # Puedes elegir un rango más pequeño si prefieres, ej: 172.24.10.0/24

services:
  vpn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openconnect-vpn
    restart: unless-stopped
    networks:
      vpn_network:
        ipv4_address: 172.24.0.2 # IP estática asignada
    volumes:
      - ./start-vpn.sh:/scripts/start-vpn.sh
    environment:
      VPN_HOST: ${VPN_HOST}
      VPN_USER: ${VPN_USER}
      VPN_PASS: ${VPN_PASS}
      VPN_GROUP: ${VPN_GROUP}
      SHARED_IPS: ${SHARED_IPS}
    cap_add:
      - NET_ADMIN        # Necesario para configurar interfaces de red
      - SYS_ADMIN        # Necesario para algunas operaciones de red
    devices:
      - /dev/net/tun     # Necesario para crear interfaces tun/tap
    sysctls:
      net.ipv4.ip_forward: 1
